openapi: 3.0.0
info:
  version: 1.15.0
  title: Tango API
  description: This is a sample for Tango API
tags:
  - name: Transfers
    description: Transfers
    externalDocs:
      description: Find out more
      url: http://tango.md
  - name: Operations
    description: Operations
    externalDocs:
      description: Find out more
      url: http://tango.md
  - name: Me
    description: Everything about your user
    externalDocs:
      description: Find out more
      url: 'http://tango.md/ru/'
  - name: Common
    description: Everything else
    externalDocs:
      description: Find out more
      url: 'http://tango.md/ru/'

paths:
  /advertising:
    get:
      tags:
        - Common
      summary: Advertising
      description: 'Get advertising info'
      responses:
        200:
          description: OK
          content:
            application/json: 
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/advertising'
              examples:
                expected:
                  value:
                    - type: browser
                      url: '<some url 1>'
                      image_url: '<some image url 1>'
                    - type: browser
                      url: '<some url 2>'
                      image_url: '<some image url 2>'
                    - type: container
                      url: '<some url 3>'
                      image_url: '<some image url 3>'
                      header:  '<some header 3>'
        401:
          $ref: '#/components/responses/unauthorized_error'
        500:
          $ref: '#/components/responses/something_wrong'
        default:
          $ref: '#/components/responses/something_wrong'

  /agents:
    get:
      tags:
        - Common
      summary: Agents list
      description: 'Get agents list'
      responses:
        200:
          description: OK
          content:
            application/json: 
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/agent'
        401:
          $ref: '#/components/responses/unauthorized_error'
        500:
          $ref: '#/components/responses/something_wrong'
        default:
          $ref: '#/components/responses/something_wrong' 

  /me:
    post:
      tags:
        - Me
      summary: Registers user
      description: 'Create your user'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/customer_basic_fields'
                - type: object
                  properties:
                    password:
                      description: The user password
                      type: string  
                      format: password
                      example: 'mystrongpassword1111'
      responses:
          200:
            description: OK
            headers:
              Authorization: 
                schema:
                  type: string
                  example: 'Bearer <TOKEN>'
          500:
            $ref: "#/components/responses/something_wrong"
          default:
            $ref: "#/components/responses/something_wrong"
  
  /authorization:
    post:
      tags:
        - Me
      summary: Authenticate user
      description: 'Authenticate your user and get JWT token'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  description: The user mail
                  type: string
                  format: email
                  example: john.doe@gmail.com
                password:
                  description: The user password
                  type: string  
                  format: password
                  example: 'mystrongpassword1111'
      responses:
          200:
            description: OK
            headers:
              Authorization: 
                schema:
                  type: string
                  example: 'Bearer <TOKEN>'
          500:
            $ref: "#/components/responses/something_wrong"
          default:
            $ref: "#/components/responses/something_wrong"

  /transfers:
    post:
      tags:
        - Transfers
      summary: Create transfer
      description: Create new transfer
      parameters:
        - in: query
          name: amount
          description: Send amount
          required: false
          schema:
            type: number
            format: double
            example: 100.0
        - in: query
          name: currency
          description: Send currency
          required: false
          schema:
            type: string
            pattern: "^[A-Z]{3}$"
            example: usd
        - in: query
          name: receiver[id]
          description: Transfer receiver
          required: false
          schema:
            type: string
            format: uuid
            example: 'df9d59bc-a237-4972-9b09-08ffdc01a399'
        - in: query
          name: destination[id]
          description: Destination location
          required: false
          schema:
            type: string
            format: uuid
            example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
        - in: query
          name: contract[id]
          description: Contract with system, rate and fee
          required: false
          schema:
            type: string
            format: uuid
            example: 'ff530c93-c7d5-46b9-ad66-88706003aded'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/transfer"
            examples:
              full:
                summary: Full info request example
                value:
                  preffered_agent:
                    id: '014d81df-ff4b-4580-9adf-a7379e888caa'
                  amount: 76.0
                  currency: 'USD'
                  destination:
                    id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                  receiver:
                    id: 'df9d59bc-a237-4972-9b09-08ffdc01a399'
                  contract:
                    id: 'ff530c93-c7d5-46b9-ad66-88706003aded'          
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transfer"
              examples:
                full:
                  value:
                    id: '49b63448-650d-4e33-a5a6-d7258724d618'
                    alias: 'QSC2774402'
                    type: 'transfer'
                    status: 'created'
                    created: '2019-08-02T08:57:59.375Z'
                    modified: '2019-08-02T08:57:59.375Z'
                    is_finalized: false
                    prefered_agent:
                      id: '014d81df-ff4b-4580-9adf-a7379e888caa'
                      name: 'Atlantis Art Materials'
                      address: '28 Tabernacle St, London EC2A 4DD, UK'
                      phone: "+44 20 7377 8855"
                      latitude: 51.52283
                      longitude: -0.08553
                      website: 'http://tango.md'
                      distance: 0.02562311926132259
                      service: 'transfer, payout, payment'
                      working_hours: '9:00AM-6:00PM'
                    amount: 100
                    currency: 'USD'
                    destination:
                      id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                      code: 'LN'
                      name: 'Lonigo'
                      country:
                        id: '19241586-e09a-4cda-9a34-31561f8097e1'
                        code: 'ITA'
                        name: 'Italy'
                    sender:
                      id: '16f7b78a-5b1f-47a2-9502-162b317f302f'
                      firstname: 'John'
                      lastname: 'Doe'
                      phone: "+44 20 7377 8855"
                      location:
                        id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                        code: 'LN'
                        name: 'Lonigo'
                        country:
                          id: '19241586-e09a-4cda-9a34-31561f8097e1'
                          code: 'ITA'
                          name: 'Italy'
                    receiver:
                      id: 'df9d59bc-a237-4972-9b09-08ffdc01a399'
                      firstname: 'Jane'
                      lastname: 'Doe'
                      phone: "+44 20 1311 7711"
                      location:
                        id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                        code: 'LN'
                        name: 'Lonigo'
                        country:
                          id: '19241586-e09a-4cda-9a34-31561f8097e1'
                          code: 'ITA'
                          name: 'Italy'
                    contract:
                      id: 'ff530c93-c7d5-46b9-ad66-88706003aded'
                      name: 'SIG ITA EUR'
                      organization:
                        id: 'ade01139-965e-4b4d-8128-cfa5ccf9ac3e'
                        code: 'SMT'
                        name: 'Sigue Money Transfer'
                      send_amount: 100
                      send_currency: 'USD'
                      receive_amount: 72.71
                      receive_currency: 'EUR'
                      exchange_rate: 0.7271
                      fee_amount: 1.5
                      total_send_amount: 101.5
        401:
          $ref: "#/components/responses/unauthorized_error"
        500:
          $ref: "#/components/responses/something_wrong"
        default:
          $ref: "#/components/responses/something_wrong"

  /operations/{operation_id}:
    get:
      tags:
        - Operations
      summary: Validate operation
      description: 'Search existing operation'
      parameters:
        - in: path
          name: operation_id
          required: true
          schema:
            type: string
          example: '6c940cb8-1a3e-43bf-a1f9-8acff2793def'
      responses:
        200:
          description: Operation exists
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/transfer'
              examples:
                minimal_transfer:
                  value:
                    id: '49b63448-650d-4e33-a5a6-d7258724d618'
                    alias: 'QSC2774402'
                    type: 'transfer'
                    status: 'created'
                    created: '2019-08-02T08:57:59.375Z'
                    modified: '2019-08-02T08:57:59.375Z'
                    is_finalized: false
                    sender:
                      id: '16f7b78a-5b1f-47a2-9502-162b317f302f'
                      firstname: 'John'
                      lastname: 'Doe'
                      phone: "+44 20 7377 8855"
                      location:
                        id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                        code: 'LN'
                        name: 'Lonigo'
                        country:
                          id: '19241586-e09a-4cda-9a34-31561f8097e1'
                          code: 'ITA'
                          name: 'Italy'
                created_transfer:
                  value:
                    id: '49b63448-650d-4e33-a5a6-d7258724d618'
                    alias: 'QSC2774402'
                    type: 'transfer'
                    status: 'created'
                    created: '2019-08-02T08:57:59.375Z'
                    modified: '2019-08-02T08:57:59.375Z'
                    is_finalized: false
                    prefered_agent:
                      id: '014d81df-ff4b-4580-9adf-a7379e888caa'
                      name: 'Atlantis Art Materials'
                      address: '28 Tabernacle St, London EC2A 4DD, UK'
                      phone: "+44 20 7377 8855"
                      latitude: 51.52283
                      longitude: -0.08553
                      website: 'http://tango.md'
                      distance: 0.02562311926132259
                      service: 'transfer, payout, payment'
                      working_hours: '9:00AM-6:00PM'
                    amount: 100
                    currency: 'USD'
                    destination:
                      id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                      code: 'LN'
                      name: 'Lonigo'
                      country:
                        id: '19241586-e09a-4cda-9a34-31561f8097e1'
                        code: 'ITA'
                        name: 'Italy'
                    sender:
                      id: '16f7b78a-5b1f-47a2-9502-162b317f302f'
                      firstname: 'John'
                      lastname: 'Doe'
                      phone: "+44 20 7377 8855"
                      location:
                        id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                        code: 'LN'
                        name: 'Lonigo'
                        country:
                          id: '19241586-e09a-4cda-9a34-31561f8097e1'
                          code: 'ITA'
                          name: 'Italy'
                    receiver:
                      id: 'df9d59bc-a237-4972-9b09-08ffdc01a399'
                      firstname: 'Jane'
                      lastname: 'Doe'
                      phone: "+44 20 1311 7711"
                      location:
                        id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                        code: 'LN'
                        name: 'Lonigo'
                        country:
                          id: '19241586-e09a-4cda-9a34-31561f8097e1'
                          code: 'ITA'
                          name: 'Italy'
                    contract:
                      id: 'ff530c93-c7d5-46b9-ad66-88706003aded'
                      name: 'SIG ITA EUR'
                      organization:
                        id: 'ade01139-965e-4b4d-8128-cfa5ccf9ac3e'
                        code: 'SMT'
                        name: 'Sigue Money Transfer'
                      send_amount: 100
                      send_currency: 'USD'
                      receive_amount: 72.71
                      receive_currency: 'EUR'
                      exchange_rate: 0.7271
                      fee_amount: 1.5
                      total_send_amount: 101.5
                executed_transfer:
                  value:
                    id: '49b63448-650d-4e33-a5a6-d7258724d618'
                    alias: 'QSC2774402'
                    type: 'transfer'
                    status: 'executed'
                    created: '2019-08-02T08:57:59.375Z'
                    modified: '2019-08-02T08:57:59.375Z'
                    is_finalized: true
                    prefered_agent:
                      id: '014d81df-ff4b-4580-9adf-a7379e888caa'
                      name: 'Atlantis Art Materials'
                      address: '28 Tabernacle St, London EC2A 4DD, UK'
                      phone: "+44 20 7377 8855"
                      latitude: 51.52283
                      longitude: -0.08553
                      website: 'http://tango.md'
                      distance: 0.02562311926132259
                      service: 'transfer, payout, payment'
                      working_hours: '9:00AM-6:00PM'
                    summary:
                      executed: '2019-08-02T08:57:59.375Z'
                      executed_agent:
                        id: '014d81df-ff4b-4580-9adf-a7379e888caa'
                        name: Atlantis Art Materials
                        address: 28 Tabernacle St, London EC2A 4DD, UK
                        phone: '+44 20 7377 8855'
                        latitude: 51.52283
                        longitude: -0.08553
                        website: 'http://tango.md'
                        distance: 0.02562311926132259
                        service: 'transfer, payout, payment'
                        working_hours: '9:00AM-6:00PM'
                      code: 'FT23098230757'
                    amount: 100
                    currency: 'USD'
                    destination:
                      id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                      code: 'LN'
                      name: 'Lonigo'
                      country:
                        id: '19241586-e09a-4cda-9a34-31561f8097e1'
                        code: 'ITA'
                        name: 'Italy'
                    sender:
                      id: '16f7b78a-5b1f-47a2-9502-162b317f302f'
                      firstname: 'John'
                      lastname: 'Doe'
                      phone: "+44 20 7377 8855"
                      location:
                        id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                        code: 'LN'
                        name: 'Lonigo'
                        country:
                          id: '19241586-e09a-4cda-9a34-31561f8097e1'
                          code: 'ITA'
                          name: 'Italy'
                    receiver:
                      id: 'df9d59bc-a237-4972-9b09-08ffdc01a399'
                      firstname: 'Jane'
                      lastname: 'Doe'
                      phone: "+44 20 1311 7711"
                      location:
                        id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                        code: 'LN'
                        name: 'Lonigo'
                        country:
                          id: '19241586-e09a-4cda-9a34-31561f8097e1'
                          code: 'ITA'
                          name: 'Italy'
                    contract:
                      id: 'ff530c93-c7d5-46b9-ad66-88706003aded'
                      name: 'SIG ITA EUR'
                      organization:
                        id: 'ade01139-965e-4b4d-8128-cfa5ccf9ac3e'
                        code: 'SMT'
                        name: 'Sigue Money Transfer'
                      send_amount: 100
                      send_currency: 'USD'
                      receive_amount: 72.71
                      receive_currency: 'EUR'
                      exchange_rate: 0.7271
                      fee_amount: 1.5
                      total_send_amount: 101.5
                created_payout:
                  value:
                    id: '9a708769-776c-48e3-b19a-bbc5395ab365'
                    alias: 'QSC9237461'
                    type: 'payout'
                    status: 'created'
                    created: '2019-08-05T08:57:59.375Z'
                    modified: '2019-08-05T08:57:59.375Z'
                    is_finalized: false
                    code: 'FT23098230757'
                    prefered_agent:
                      id: '014d81df-ff4b-4580-9adf-a7379e888caa'
                      name: 'Atlantis Art Materials'
                      address: '28 Tabernacle St, London EC2A 4DD, UK'
                      phone: "+44 20 7377 8855"
                      latitude: 51.52283
                      longitude: -0.08553
                      website: 'http://tango.md'
                      distance: 0.02562311926132259
                      service: 'transfer, payout, payment'
                      working_hours: '9:00AM-6:00PM'
                    sender:
                      id: '16f7b78a-5b1f-47a2-9502-162b317f302f'
                      firstname: 'John'
                      lastname: 'Doe'
                      phone: "+44 20 7377 8855"
                      location:
                        id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                        code: 'LN'
                        name: 'Lonigo'
                        country:
                          id: '19241586-e09a-4cda-9a34-31561f8097e1'
                          code: 'ITA'
                          name: 'Italy'
                    receiver:
                      id: 'df9d59bc-a237-4972-9b09-08ffdc01a399'
                      firstname: 'Jane'
                      lastname: 'Doe'
                      phone: "+44 20 1311 7711"
                      location:
                        id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                        code: 'LN'
                        name: 'Lonigo'
                        country:
                          id: '19241586-e09a-4cda-9a34-31561f8097e1'
                          code: 'ITA'
                          name: 'Italy'
                    contract:
                      id: 'ff530c93-c7d5-46b9-ad66-88706003aded'
                      name: 'SIG ITA EUR'
                      organization:
                        id: 'ade01139-965e-4b4d-8128-cfa5ccf9ac3e'
                        code: 'SMT'
                        name: 'Sigue Money Transfer'
                      receive_amount: 72.71
                      receive_currency: 'EUR'
                executed_payout:
                  value:
                    id: '9a708769-776c-48e3-b19a-bbc5395ab365'
                    alias: 'QSC9237461'
                    type: 'payout'
                    status: 'created'
                    created: '2019-08-05T08:57:59.375Z'
                    modified: '2019-08-05T08:57:59.375Z'
                    is_finalized: true
                    code: 'FT23098230757'
                    prefered_agent:
                      id: '014d81df-ff4b-4580-9adf-a7379e888caa'
                      name: 'Atlantis Art Materials'
                      address: '28 Tabernacle St, London EC2A 4DD, UK'
                      phone: "+44 20 7377 8855"
                      latitude: 51.52283
                      longitude: -0.08553
                      website: 'http://tango.md'
                      distance: 0.02562311926132259
                      service: 'transfer, payout, payment'
                      working_hours: '9:00AM-6:00PM'
                    summary:
                      executed: '2019-08-02T08:57:59.375Z'
                      executed_agent:
                        id: '014d81df-ff4b-4580-9adf-a7379e888caa'
                        name: Atlantis Art Materials
                        address: 28 Tabernacle St, London EC2A 4DD, UK
                        phone: '+44 20 7377 8855'
                        latitude: 51.52283
                        longitude: -0.08553
                        website: 'http://tango.md'
                        distance: 0.02562311926132259
                        service: 'transfer, payout, payment'
                        working_hours: '9:00AM-6:00PM'
                    sender:
                      id: '16f7b78a-5b1f-47a2-9502-162b317f302f'
                      firstname: 'John'
                      lastname: 'Doe'
                      phone: "+44 20 7377 8855"
                      location:
                        id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                        code: 'LN'
                        name: 'Lonigo'
                        country:
                          id: '19241586-e09a-4cda-9a34-31561f8097e1'
                          code: 'ITA'
                          name: 'Italy'
                    receiver:
                      id: 'df9d59bc-a237-4972-9b09-08ffdc01a399'
                      firstname: 'Jane'
                      lastname: 'Doe'
                      phone: "+44 20 1311 7711"
                      location:
                        id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                        code: 'LN'
                        name: 'Lonigo'
                        country:
                          id: '19241586-e09a-4cda-9a34-31561f8097e1'
                          code: 'ITA'
                          name: 'Italy'
                    contract:
                      id: 'ff530c93-c7d5-46b9-ad66-88706003aded'
                      name: 'SIG ITA EUR'
                      organization:
                        id: 'ade01139-965e-4b4d-8128-cfa5ccf9ac3e'
                        code: 'SMT'
                        name: 'Sigue Money Transfer'
                      receive_amount: 72.71
                      receive_currency: 'EUR'
components:
  securitySchemes:
    authentication:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    unauthorized_error:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
    something_wrong:
      description: Something went wrong
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              error_code:
                type: string
          examples:
            expected:
              value:
                error: "<error reason>"
                error_code: <some error code>
  schemas:
    advertising:
      required: 
        - type
        - url
        - image_url
      properties:
        type:
          description: Advertising type
          type: string
          enum: [browser, container]
          example: browser
        url:
          description: Advertising url
          type: string
          format: url
          example: 'https://www.google.com'
        image_url:
          description: Advertising image url
          type: string
          format: url
          example: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1024px-Google_%22G%22_Logo.svg.png'
        header:
          description: Advertising header, for container type only
          type: string
          example: 'Some intresting header'

    correspondent:
      required:
        - id
        - firstname
        - lastname
        - location
        - is_user
      properties:
        id:
          type: string
          format: uuid
          example: '16f7b78a-5b1f-47a2-9502-162b317f302f'
        firstname:
          description: The user first name
          type: string
          example: John
        lastname:
          description: The user last name
          type: string
          example: Doe
        location:
          $ref: "#/components/schemas/city"
        is_user:
          type: boolean
          description: Indicates if it is correspondent generated from user based on your phone book
        phone:
          description: The user phone
          type: string
          format: phone
          example: "+44 20 7377 8855"

    customer_basic_fields:
      required:
        - firstname
        - lastname
        - email
        - birthdate
        - gender
        - phone
      properties:
        firstname:
          description: The user first name
          type: string
          example: John
        lastname:
          description: The user last name
          type: string
          example: Doe
        email:
          description: The user mail
          type: string
          format: email
          example: john.doe@gmail.com
        birthdate:
          description: The user birth date
          type: string
          format: date
          example: "1970-01-01"
        gender:
          description: The user gender
          type: string
          enum:
            - male
            - female
          example: male
        phone:
          description: The user phone
          type: string
          format: phone
          example: "+44 20 7377 8855"

    customer_basic_profile:
      required:
        - id
      allOf:
        - $ref: "#/components/schemas/customer_basic_fields"
      properties:
        id:
          type: string
          format: uuid
          example: '16f7b78a-5b1f-47a2-9502-162b317f302f'

    id_document_type:
      allOf:
        - $ref: "#/components/schemas/identifiable_record"
      properties:
        id:
          example: '6bbfed96-75e3-40b8-a620-0d2524638c9e'
        code:
          description: Identification document code
          example: 'NAT'
        name:
          description: Identification document name
          example: 'National ID'

    customer_full_profile:
      allOf:
        - $ref: "#/components/schemas/customer_basic_profile"
        - type: object
          properties:
            personal_number:
              description: Social/National/Insurance number
              type: string
              example: 'SN1998398754'
            id_document_type:
              $ref: "#/components/schemas/id_document_type"
            id_document_number:
              description: Identification document number
              type: string
              example: 'AB1299734'
            location:
              description: Customer resident city
              allOf:
                - $ref: "#/components/schemas/city"
    identifiable_record:
      required:
        - id
        - name
        - code
      properties:
        id:
          type: string
          format: uuid
          example: 'df697a99-634d-4ed7-9fdc-ef8cfb12278e'
        code:
          type: string
        name:
          type: string
    amount:
      type: number
      format: double
      example: 10.0
    currency_code:
      type: string
      pattern: "^[A-Z]{3}$"
      example: USD
    country:
      allOf:
        - $ref: "#/components/schemas/identifiable_record"
        - type: object
          properties:
            id:
              example: '19241586-e09a-4cda-9a34-31561f8097e1'
            code:
              description: Country code
              example: 'ITA'
            name:
              description: Country name
              example: 'Italy'
    city:
      allOf:
        - $ref: "#/components/schemas/identifiable_record"
        - type: object
          properties:
            id:
              example: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
            code:
              description: City code
              example: 'LN'
            name:
              description: City name
              example: 'Lonigo'
            country:
              $ref: "#/components/schemas/country"
    agent:
      required:
        - id
        - name
        - address
        - phone
        - working_hours
        - latitude
        - longitude
        - distance
      properties:
        id:
          type: string
          format: uuid
          example: '014d81df-ff4b-4580-9adf-a7379e888caa'
        name:
          description: Agent name
          type: string
          example: 'Atlantis Art Materials'
        address:
          description: Agent address
          type: string
          example: '28 Tabernacle St, London EC2A 4DD, UK'
        phone:
          description: Agent phone
          type: string
          format: phone
          example: '+44 20 7377 8855'
        latitude:
          description: Latitude
          type: number
          format: double
          example: 51.522830
        longitude:
          description: Longitude
          type: number
          format: double
          example: -0.085530
        website:
          description: Agent website
          type: string
          format: url
          example: 'http://tango.md'
        distance:
          description: Distance to agent
          type: number
          format: double
          example: 0.025623119261322588
        service:
          description: Services provided by Agent
          type: string
          example: 'transfer, payout, payment'
        working_hours:
          description: Agent working hours. Defined as simple string, but should be implemented as complex object with week days and from and to fields.
          type: string
          example: '9:00AM-6:00PM'
    operation_type:
      type: string
      description: Operation type
      enum:
        - transfer
        - payout
        - payment
    operation_status:
      type: string
      description: Set of common operation states
      enum:
        - created
        - executed
        - canceled
    opeartion_summary:
      properties:
        executed:
          type: string
          format: date-time
        executed_agent:
          allOf:
            - $ref: "#/components/schemas/agent"
          description: Agent that executed the operation
        code:
          type: string
          description: Code assigned to the operation on successful execution. Usually it comdes from external system (eg. Money Transfer System)
          example: 'FT23098230757'
    operation:
      required:
        - id
        - alias
        - type
        - status
        - created
        - modified
        - is_finalized
      properties:
        id:
          type: string
          format: uuid
          example: '49b63448-650d-4e33-a5a6-d7258724d618'
        alias:
          description: Human-friendly opeartion alternative name suitalbe for reference to share with others and for manual search
          type: string
          example: 'QSC2774402'
        type:
          $ref: "#/components/schemas/operation_type"
        status:
          $ref: "#/components/schemas/operation_status"
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
        is_finalized:
          type: boolean
          default: false
        prefered_agent:
          $ref: "#/components/schemas/agent"
        summary:
          allOf:
            - $ref: "#/components/schemas/opeartion_summary"
          description: Execution summary of the operation. For future use could include additional fields.
    organization:
      allOf:
        - $ref: "#/components/schemas/identifiable_record"
        - type: object
          properties:
            id:
              example: 'ade01139-965e-4b4d-8128-cfa5ccf9ac3e'
            code:
              description: Organization short name (code, optional)
              example: 'SMT'
            name:
              description: Organization name
              example: 'Sigue Money Transfer'
    transfer_contract:
      description: Proposal details from a certain organization for the requested transfer.
      required:
        - id
        - name
        - send_amount
        - send_currency
        - receive_amount
        - receive_currency
        - exchange_rate
        - fee_amount
        - total_send_amount
        - total_receive_amount
      properties:
        id:
          type: string
          format: uuid
          example: 'ff530c93-c7d5-46b9-ad66-88706003aded'
        name:
          description: Tunnel name
          type: string
          example: 'SIG ITA EUR'
        organization:
          $ref: "#/components/schemas/organization"
        send_amount:
          allOf:
            - $ref: "#/components/schemas/amount"
          description: Amount in source currency to send
          example: 100.0
        send_currency:
          allOf:
            - $ref: "#/components/schemas/currency_code"
          description: Currency code of amount to send
          example: 'USD'
        receive_amount:
          description: Destination amount paid to receiver
          allOf:
            - $ref: "#/components/schemas/amount"
          example: 72.71
        receive_currency:
          description: Destination currency code of amount paid to receiver
          allOf:
            - $ref: "#/components/schemas/currency_code"
          example: 'EUR'
        exchange_rate:
          description: Exchange rate
          type: number
          format: float
          example: 0.7271
        fee_amount:
          description: Fee amount in source currency
          allOf:
            - $ref: "#/components/schemas/amount"
          example: 1.5
        total_send_amount:
          description: Total amount in source currency to pay including fee
          allOf:
            - $ref: "#/components/schemas/amount"
          example: 101.5
    transfer:
      allOf:
        - $ref: "#/components/schemas/operation"
        - type: object
          required:
            - sender
          properties:
            amount:
              description: Amount to send
              allOf:
                - $ref: "#/components/schemas/amount"
              example: 100.0
            currency:
              allOf:
                - $ref: "#/components/schemas/currency_code"
              description: Currency code of the operation
              example: 'USD'
            code:
              type: string
              description: Code assigned to the operation on successful execution. Usually it comdes from external system (eg. Money Transfer System)
              example: 'FT23098230757'
            destination:
              description: Destination city where to send money
              allOf:
                - $ref: "#/components/schemas/city"
            sender:
              $ref: "#/components/schemas/correspondent"
            receiver:
              allOf:
                - $ref: "#/components/schemas/correspondent"
              example:
                id: 'df9d59bc-a237-4972-9b09-08ffdc01a399'
                firstname: 'Jane'
                lastname: 'Doe'
                phone: "+44 20 1311 7711"
                location:
                  id: 'f3d7a372-dcb9-4f86-b6d3-3639e4a70a4b'
                  code: 'LN'
                  name: 'Lonigo'
                  country:
                    id: '19241586-e09a-4cda-9a34-31561f8097e1'
                    code: 'ITA'
                    name: 'Italy'
            contract:
              $ref: "#/components/schemas/transfer_contract"
